### PR TITLE
Avoids segfault when p_section is empty

### PR DESCRIPTION
**Pull request by barhom**
Credit to Georgi Chorbadzhiyski

### CODE REVIEW

**Comment by cmassiot** [comment]
The SDT is invalid if a section is missing. Do we want to print incomplete tables? If so, why only SDT?

**Comment by barhom** [comment]
@cmassiot 
In my use case for example, I use the SDT to populate my own database of what kind of services are on the transponder.

If dvblastctl segfaults I am unable to process anything from the sdt. I believe we all agree that dvblastctl should not segfault even though SDT is invalid.

I would prefer to print whatever is valid of the SDT and skip whatever is invalid, however, I do understand that other people might have an alternative opinion about this.

How do you suggest we handle this?

**Comment by cmassiot** [comment]
From a user point of view, I'd expect dvblastctl to return a complete SDT, or an error code. If I receive an incomplete SDT, I may deduce that the service I am looking for doesn't exist and raise an alarm, although nothing went wrong in reality.

**Comment by barhom** [comment]
I think we have to take a real-world example to make the best decision on how to fix this.
[28.2E, 11538V](https://www.flysat.com/astra28.php)

Without the patch:

> new SDT actual tsid=2094 version=10 onid=2
>   * service sid=22601 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="ATN Bangla UK"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=42 value=1d0031df221efe534deede4d357182957eedaae3024d571832858d0cf2d6cd2c6ab8c16c191a7ef6e7b5
>   * service sid=22602 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="CHSTV"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=69 value=1d0131df2ae1dccb7955c60a51eab8c11355c610f903de39a2ee4ebaed75647b6e8007fe566944755c608984a34bfb2ee4ebaed75646c6f76f269ab8c14abf76dcde5dfe95
>   * service sid=22603 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="Ahlebait TV"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=121 value=1d0111df38af4fe12adaae3013ca1a755c614832a7f44da145af211d75daeac8eab87b6e85b0e475153e1aae303a9a6a7c93d5c60a51d8d571832858dc9d75daeac8eab8c1d7c2c6ab8c14a1369ab8c14abf76d07755c60841db594b737dc57a7f0956d571809d8d4f927d571822ee2bd3f84ab6ab8c04fb55
>   * service sid=22604 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="Xpanded TV2"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=140 value=1d00313f2afb6355c605baae3024dccd7aae305cd5718516ab8c21f71b78f5718127a755c6027b84f0f0dd16cf15aae30b6d59a5b14b786ab8c21b0d571834d5c61b56dc0be606ab8c21f7097808637430eb35b997ab8c36ad86956d571846eab8c0b6c64acd355c610fbaaf422ba2af1629b6b1f52ae3052fd57182268641b73571834bff2cb5718348218a
>   * service sid=22605 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="HUM EUROPE"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=144 value=1d00d1df2ab57627741577ac8215e82c6ab8c1b755c60d1aae3087d5718206aad5d89dd7f618ca06ab8c1170acc050697b1aae306887c8355c611baae3087d571807ee20597dc9d75daeac8d8d52497d91d5718346f76f269ab8c14abf76c391c653586ab8c14f55c60701630792cd02c60391c2c6e4ce055c60a51eab8c1f4355c6049aae305b06469f87238ca6b0ed
>   * service sid=22606 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="TalkingPictures"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=142 value=1d00d038b3128faae308dd571843eaa5179801a5d1ccb5feab8c1a32651edacaff5718439656820c37837938632c37f8ebe1637275fa57c3196e4bfc75f0b185cd2055c60a51e155e5ad2f0d571809eab8c12b2b69a53b6eb7d5c60b9aae307ed5718346ab8c21f1497836ab8c093465f2de0da3fac355c608baae3042d5718126ab8c04f55c609d571846923daa
> Segmentation fault

With the patch:
> new SDT actual tsid=2094 version=10 onid=2
>   * service sid=22601 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="ATN Bangla UK"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=42 value=1d0031df221efe534deede4d357182957eedaae3024d571832858d0cf2d6cd2c6ab8c16c191a7ef6e7b5
>   * service sid=22602 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="CHSTV"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=69 value=1d0131df2ae1dccb7955c60a51eab8c11355c610f903de39a2ee4ebaed75647b6e8007fe566944755c608984a34bfb2ee4ebaed75646c6f76f269ab8c14abf76dcde5dfe95
>   * service sid=22603 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="Ahlebait TV"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=121 value=1d0111df38af4fe12adaae3013ca1a755c614832a7f44da145af211d75daeac8eab87b6e85b0e475153e1aae303a9a6a7c93d5c60a51d8d571832858dc9d75daeac8eab8c1d7c2c6ab8c14a1369ab8c14abf76d07755c60841db594b737dc57a7f0956d571809d8d4f927d571822ee2bd3f84ab6ab8c04fb55
>   * service sid=22604 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="Xpanded TV2"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=140 value=1d00313f2afb6355c605baae3024dccd7aae305cd5718516ab8c21f71b78f5718127a755c6027b84f0f0dd16cf15aae30b6d59a5b14b786ab8c21b0d571834d5c61b56dc0be606ab8c21f7097808637430eb35b997ab8c36ad86956d571846eab8c0b6c64acd355c610fbaaf422ba2af1629b6b1f52ae3052fd57182268641b73571834bff2cb5718348218a
>   * service sid=22605 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="HUM EUROPE"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=144 value=1d00d1df2ab57627741577ac8215e82c6ab8c1b755c60d1aae3087d5718206aad5d89dd7f618ca06ab8c1170acc050697b1aae306887c8355c611baae3087d571807ee20597dc9d75daeac8d8d52497d91d5718346f76f269ab8c14abf76c391c653586ab8c14f55c60701630792cd02c60391c2c6e4ce055c60a51eab8c1f4355c6049aae305b06469f87238ca6b0ed
>   * service sid=22606 eit_schedule eit_pf running=4
>     - desc 48 service type=0x1 provider="BSkyB" service="TalkingPictures"
>     - desc 49 country_availability available=1 country=GBR
>     - desc 49 country_availability available=1 country=IRL
>     - desc 5f private_data specifier=0x00000002
>     - desc b2 unknown length=142 value=1d00d038b3128faae308dd571843eaa5179801a5d1ccb5feab8c1a32651edacaff5718439656820c37837938632c37f8ebe1637275fa57c3196e4bfc75f0b185cd2055c60a51e155e5ad2f0d571809eab8c12b2b69a53b6eb7d5c60b9aae307ed5718346ab8c21f1497836ab8c093465f2de0da3fac355c608baae3042d5718126ab8c04f55c609d571846923daa
> end SDT


Both before and after patch shows
* service sid=22601
* service sid=22602
* service sid=22603
* service sid=22604
* service sid=22605
* service sid=22606


What we both agree on:
dvblastctl should not segfault

What we disagree on:
Should dvblastctl show the SDT at all or should it just give an error?

I believe that it should still show whatever SDT is available. It can also show an error perhaps.
But I dont think dvblastctl should completely remove the SDT and just show an error because then (in my use case) I wouldn't be able to parse the output of the working sids.

I'll leave it to dvblast/bitstream/videolan developers to decide how to fix this if this pull request is not good enough.

**Comment by cmassiot** [comment]
Is it possible to have a recording of this stream ? I don't have a dish on 28.2E. Is it reproduceable with the UDP input ?

**Comment by barhom** [comment]
@cmassiot 
Download transponder.ts and transponder.aux from https://drive.google.com/file/d/140967m4R4e4PUZCQRLXOSLJ4uxU6IGkF/view?usp=sharing 

it is in a zip file. Hopefully you can reproduce the segfault.

**Comment by cmassiot** [comment]
Please try again with attached patch.

diff --git a/dvblastctl.c b/dvblastctl.c
index 37d96e8..ccdca6d 100644
--- a/dvblastctl.c
+++ b/dvblastctl.c
@@ -647,8 +647,8 @@ int main( int i_argc, char **ppsz_argv )
     } while ( i_received < i_packet_size );
 
     clean_client_socket();
-    if ( i_size < COMM_HEADER_SIZE )
-        return_error( "Cannot recv from comm socket, size:%zd (%s)", i_size, strerror(errno) );
+    if ( i_packet_size < COMM_HEADER_SIZE )
+        return_error( "Cannot recv from comm socket, size:%"PRIu32" (%s)", i_packet_size, strerror(errno) );
 
     /* Process answer */
     if ( p_buffer[0] != COMM_HEADER_MAGIC )
@@ -684,7 +684,7 @@ int main( int i_argc, char **ppsz_argv )
     case RET_SDT:
     {
         uint8_t *p_flat_data = p_buffer + COMM_HEADER_SIZE;
-        unsigned int i_flat_data_size = i_size - COMM_HEADER_SIZE;
+        unsigned int i_flat_data_size = i_packet_size - COMM_HEADER_SIZE;
         uint8_t **pp_sections = psi_unpack_sections( p_flat_data, i_flat_data_size );
         if ( !pp_sections )
         {
@@ -741,7 +741,7 @@ int main( int i_argc, char **ppsz_argv )
         int ret = 1;
         struct ret_frontend_status *p_ret =
             (struct ret_frontend_status *)&p_buffer[COMM_HEADER_SIZE];
-        if ( i_size != COMM_HEADER_SIZE + sizeof(struct ret_frontend_status) )
+        if ( i_packet_size != COMM_HEADER_SIZE + sizeof(struct ret_frontend_status) )
             return_error( "Bad frontend status" );
 
         if ( i_print_type == PRINT_XML )
@@ -889,7 +889,7 @@ int main( int i_argc, char **ppsz_argv )
     {
         struct ret_mmi_status *p_ret =
             (struct ret_mmi_status *)&p_buffer[COMM_HEADER_SIZE];
-        if ( i_size != COMM_HEADER_SIZE + sizeof(struct ret_mmi_status) )
+        if ( i_packet_size != COMM_HEADER_SIZE + sizeof(struct ret_mmi_status) )
             return_error( "Bad MMI status" );
 
         printf("CA interface with %d %s, type:\n", p_ret->caps.slot_num,
@@ -923,7 +923,7 @@ int main( int i_argc, char **ppsz_argv )
     {
         struct ret_mmi_slot_status *p_ret =
             (struct ret_mmi_slot_status *)&p_buffer[COMM_HEADER_SIZE];
-        if ( i_size < COMM_HEADER_SIZE + sizeof(struct ret_mmi_slot_status) )
+        if ( i_packet_size < COMM_HEADER_SIZE + sizeof(struct ret_mmi_slot_status) )
             return_error( "Bad MMI slot status" );
 
         printf("CA slot #%u: ", p_ret->sinfo.num);
@@ -956,10 +956,10 @@ int main( int i_argc, char **ppsz_argv )
     {
         struct ret_mmi_recv *p_ret =
             (struct ret_mmi_recv *)&p_buffer[COMM_HEADER_SIZE];
-        if ( i_size < COMM_HEADER_SIZE + sizeof(struct ret_mmi_recv) )
+        if ( i_packet_size < COMM_HEADER_SIZE + sizeof(struct ret_mmi_recv) )
             return_error( "Bad MMI recv" );
 
-        en50221_UnserializeMMIObject( &p_ret->object, i_size
+        en50221_UnserializeMMIObject( &p_ret->object, i_packet_size
           - COMM_HEADER_SIZE - ((void *)&p_ret->object - (void *)p_ret) );
 
         switch ( p_ret->object.i_object_type )

**Comment by barhom** [comment]
The patch works and removes the segfault.

Except for changing all the variable name from i_packet to i_packet_size the only other difference I see is,

+        return_error( "Cannot recv from comm socket, size:%"PRIu32" (%s)", i_packet_size, strerror(errno) );

Unsure what that does, but great job!

**Pull request closed without merging**
